name: Deploy to AWS

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Install AWS SAM CLI
        run: |
          curl -Lo sam-cli.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
          unzip sam-cli.zip -d sam-installation
          sudo mv sam-installation/aws-sam-cli /usr/local/bin/sam
          sam --version

      - name: Build and Deploy with SAM
        run: |
          sam build
          sam deploy --no-confirm-changeset --stack-name multi-tenant-onboarding --capabilities CAPABILITY_IAM
